### ISSUE TITLE
Mysql failed to start

### ISSUE THREAD

**Issue by RichardPiel** [pyguerder/bitbucket-pipelines-php72#4]
Hello,

I'm trying to use your config but i got an error when i try to start mysql, below the error :

```
+ service mysql start
 * Starting MySQL database server mysqld
   ...fail!
```

And below my bitbucket-pipelines.yml : 

```

image: pyguerder/bitbucket-pipelines-php72

pipelines:
  branches:
    develop:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - service mysql start
            - mysql -h localhost -u root -proot -e "CREATE DATABASE test;"  
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - bin/cake migrations migrate
            - vendor/bin/phpunit
          services: 
            - mysql
      - step:
            name: Deploy to dev
            deployment: test
            script:
              - apt-get update
              - apt-get install ssh -y
              - apt-get install rsync -y
              - rsync -zrSlh --stats $BITBUCKET_CLONE_DIR/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH;
              - ssh $DEPLOY_USER@$DEPLOY_HOST "cd public_html && bin/cake migrations migrate"
    master:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - vendor/bin/phpunit
            #- php artisan key:generate
            #- php artisan migrate
            #- phpunit
      - step:
            name: Deploy to production
            deployment: production
            script:
              - apt-get update
              - apt-get install ssh -y
              - apt-get install rsync -y
              - rsync -zrSlh --stats $BITBUCKET_CLONE_DIR/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH;
              - ssh $DEPLOY_USER@$DEPLOY_HOST "cd public_html && bin/cake migrations migrate"
definitions: 
  services: 
    mysql: 
      image: mysql:5.7 
      variables: 
        MYSQL_DATABASE: 'test'
        MYSQL_USER: 'test_user'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_PASSWORD: 'test_user_password'
```

Can you help me?

Thanks
